---
- name: Install Flatpak software
  become: true
  community.general.flatpak:
    name:
      - com.github.tchx84.Flatseal # Band-aid for Flatpaks
      - it.mijorus.gearlever # Band-aid for AppImages
      - com.bitwarden.desktop
      - org.gimp.GIMP
  tags: flatpak
