---
- name: Bin folder in homedir
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/bin"
    state: directory
    mode: "0755"
  tags: user

- name: .nanorc
  ansible.builtin.copy:
    dest: ~/.nanorc
    src: files/nanorc
    mode: "0644"
  tags: user

- name: .vimrc
  ansible.builtin.copy:
    dest: ~/.vimrc
    src: files/vimrc
    mode: "0644"
  tags: user

- name: .tmux.conf
  ansible.builtin.copy:
    dest: ~/.tmux.conf
    src: files/tmux.conf
    mode: "0644"
  tags: user

- name: terminator config dir
  ansible.builtin.file:
    state: directory
    path: ~/.config/terminator
    mode: "0755"
  tags: user

- name: terminator config
  ansible.builtin.copy:
    src: files/terminator.config
    dest: ~/.config/terminator/config
    mode: "0644"
  tags: user
